import jsPDF from "jspdf";
import { ScanResult } from "@/utils/api";

function buildShareSummary(result: ScanResult): string {
  const topFinding = result.findings[0]?.title ?? "No major critical findings";
  return [
    `Domain: ${result.domain}`,
    `Risk: ${result.risk.label} (${result.risk.score}/100)`,
    `Key finding: ${topFinding}`,
  ].join("\n");
}

export function downloadJsonReport(result: ScanResult): void {
  const payload = JSON.stringify(result, null, 2);
  const blob = new Blob([payload], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `quantumshield-report-${result.domain}.json`;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function downloadPdfReport(result: ScanResult): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const lineHeight = 16;
  let y = 50;

  const writeLine = (text: string, fontSize = 11, weight: "normal" | "bold" = "normal") => {
    doc.setFont("helvetica", weight);
    doc.setFontSize(fontSize);
    const lines = doc.splitTextToSize(text, 520);
    doc.text(lines, 40, y);
    y += lines.length * lineHeight;
    if (y > 760) {
      doc.addPage();
      y = 50;
    }
  };

  writeLine("QuantumShield AI Security Report", 18, "bold");
  writeLine(`Scanned Domain: ${result.domain}`, 12, "bold");
  writeLine(`Generated At: ${new Date(result.scanned_at).toLocaleString()}`);
  writeLine(`Overall Risk: ${result.risk.label} (${result.risk.score}/100)`);
  y += 8;

  writeLine("Encryption", 13, "bold");
  writeLine(`TLS Version: ${result.encryption.protocol}`);
  writeLine(`Cipher Suite: ${result.encryption.cipher_suite}`);
  writeLine(`Key Length: ${result.encryption.key_bits}-bit`);
  y += 8;

  writeLine("Top Findings", 13, "bold");
  if (result.findings.length === 0) {
    writeLine("No major findings detected.");
  } else {
    result.findings.slice(0, 8).forEach((finding, index) => {
      writeLine(`${index + 1}. [${finding.severity.toUpperCase()}] ${finding.title}`);
      writeLine(`   ${finding.detail}`);
    });
  }
  y += 8;

  writeLine("Recommendations", 13, "bold");
  result.recommendations.slice(0, 8).forEach((item, index) => {
    writeLine(`${index + 1}. (${item.priority.toUpperCase()}) ${item.title}`);
    writeLine(`   ${item.description}`);
  });

  doc.save(`quantumshield-report-${result.domain}.pdf`);
}

export function buildMailtoLink(result: ScanResult): string {
  const subject = encodeURIComponent("QuantumShield AI Security Report");
  const body = encodeURIComponent(
    `${buildShareSummary(result)}\n\nGenerated by QuantumShield AI.`,
  );
  return `mailto:?subject=${subject}&body=${body}`;
}

export function buildWhatsappLink(result: ScanResult): string {
  const message = encodeURIComponent(
    `${buildShareSummary(result)}\nAction: Review and remediate with QuantumShield AI.`,
  );
  return `https://wa.me/?text=${message}`;
}
